/* Auto-generated by scripts/generate-trainer-platform.mjs. Do not edit directly. */
import type { TrainerPlatformContractMap } from './trainerContract';

export const TRAINER_PLATFORM_CONTRACTS: TrainerPlatformContractMap = {
  "classic2": {
    "id": "classic2",
    "title": "Classic 2 · Structure of Magic",
    "subtitle": "קוראים טקסט קצר, מסמנים איפה הקטגוריה באמת מופיעה, ובודקים הכול מול טבלת ברין אחת שנשארת תמיד באותו סדר.",
    "familyLabel": "משפחת קלאסיק",
    "quickStartLabel": "מתחילים מכאן",
    "startActionLabel": "התחל סבב",
    "settingsTitle": "לוח הבקרה של Classic 2",
    "settingsSubtitle": "מכווננים מה לתרגל, כמה עומס לשים, ואיך לראות את מפת ברין, בלי לאבד את נקודת ההתחלה המהירה.",
    "helperSteps": [
      {
        "title": "1. בחר/י או השאר/י ברירת מחדל",
        "description": "אפשר להתחיל ישר או לכוונן עומס, תצוגה וקטגוריות."
      },
      {
        "title": "2. קרא/י ועבוד/י בתוך הטקסט",
        "description": "בחר/י קטגוריה אחת ונסה/י לזהות איפה היא באמת מופיעה."
      },
      {
        "title": "3. בדוק/י, למד/י והמשך/י",
        "description": "קבל/י משוב, פתח/י רמז או פתרון, ואז עבור/י לסבב הבא."
      }
    ],
    "processSteps": [
      {
        "id": "prepare",
        "label": "1. מכוונים את הסשן",
        "shortLabel": "מכוונים",
        "description": "אפשר להישאר עם ברירת המחדל או למקד תחום, עומס ותצוגה."
      },
      {
        "id": "choose-category",
        "label": "2. בוחרים קטגוריה",
        "shortLabel": "קטגוריה",
        "description": "עובדים מול מפת ברין קנונית כדי לבנות זיכרון מסך יציב."
      },
      {
        "id": "mark-text",
        "label": "3. מסמנים בתוך הטקסט",
        "shortLabel": "מסמנים",
        "description": "מחפשים איפה הקטגוריה באמת מופיעה ולא מסתמכים על תחושה כללית."
      },
      {
        "id": "check",
        "label": "4. בודקים את הבחירה",
        "shortLabel": "בודקים",
        "description": "מקבלים משוב, רמז או פתרון ורואים אם הסימון היה מלא ומדויק."
      },
      {
        "id": "continue",
        "label": "5. ממשיכים לסבב הבא",
        "shortLabel": "ממשיכים",
        "description": "לוקחים את הדיוק לסשן הבא בלי לאבד את אותו סדר מסך."
      }
    ],
    "supportRailMode": "breen-map",
    "settingsGroups": [
      "what-to-practice",
      "session-load",
      "display-mode",
      "categories",
      "difficulty",
      "text-source"
    ],
    "mobilePriorityOrder": [
      "start",
      "purpose",
      "helper-steps",
      "main",
      "support"
    ],
    "wrapper": {
      "pageTitle": "Classic 2 - Structure of Magic Trainer",
      "mountId": "classic2-root",
      "loadingTitle": "טוען את Classic 2...",
      "loadingText": "מכין את סביבת האימון של Structure of Magic עם טקסט, קטגוריות ומשוב חי.",
      "errorTitle": "שגיאה בטעינת Classic 2",
      "navLinks": [
        {
          "href": "index.html",
          "label": "חזרה לדף הראשי"
        },
        {
          "href": "classic_classic_trainer.html",
          "label": "Classic Classic"
        },
        {
          "href": "iceberg_templates_trainer.html",
          "label": "Iceberg Templates"
        },
        {
          "href": "scenario_trainer.html",
          "label": "$1תמונות מחיי היום"
        }
      ],
      "accent": {
        "primary": "#1d4ed8",
        "border": "#bfdbfe",
        "glow": "rgba(59,130,246,0.18)",
        "background": "radial-gradient(circle at 10% 10%, #dbeafe, #f8fafc 45%, #ecfeff)"
      },
      "standalone": {
        "htmlFile": "classic2_trainer.html",
        "manifestKey": "_classic2",
        "bundlePath": "js/classic2-trainer.bundle.js",
        "buildMetaGlobalKey": "__CLASSIC2_BUILD_META__"
      }
    }
  },
  "classic-classic": {
    "id": "classic-classic",
    "title": "Classic Classic · זיהוי תבניות",
    "subtitle": "שומעים משפט, מזהים את המבנה הלשוני המרכזי, ובודקים למה הבחירה מדויקת או מפספסת.",
    "familyLabel": "משפחת קלאסיק",
    "quickStartLabel": "פתיחת תרגול",
    "startActionLabel": "התחל תרגול",
    "settingsTitle": "הגדרות Classic Classic",
    "settingsSubtitle": "מכווננים מצב, קושי, עומס ומשפחת תרגול, בלי להפוך את ההגדרות למחסום לפני תחילת הסשן.",
    "helperSteps": [
      {
        "title": "1. משאירים ברירת מחדל או משנים",
        "description": "אפשר להתחיל מיד או לפתוח הגדרות קצרות לפני הכניסה לסשן."
      },
      {
        "title": "2. קוראים ובוחרים תשובה",
        "description": "קולטים את המשפט, מזהים את השלב, ובוחרים את התשובה המתאימה."
      },
      {
        "title": "3. בודקים, מבינים, ממשיכים",
        "description": "מקבלים הסבר יציב, מסכמים את השאלה, וממשיכים לסבב הבא."
      }
    ],
    "processSteps": [
      {
        "id": "context",
        "label": "שלב 1 — שומעים את המשפט",
        "shortLabel": "שומעים",
        "description": "מקבלים הקשר מלא ורואים איפה כדאי לעצור את המבט."
      },
      {
        "id": "question",
        "label": "שלב 2 — בוחרים שאלת בירור",
        "shortLabel": "שאלת בירור",
        "description": "מחזירים מידע חסר במקום לקפוץ לפרשנות או פתרון."
      },
      {
        "id": "problem",
        "label": "שלב 3 — מזהים את המבנה",
        "shortLabel": "המבנה",
        "description": "נותנים שם לפער הלשוני המרכזי."
      },
      {
        "id": "goal",
        "label": "שלב 4 — מחדדים מה חסר",
        "shortLabel": "מה חסר",
        "description": "מנסחים איזה מידע צריך להחזיר כדי שהמפה תהיה בת-בדיקה."
      },
      {
        "id": "summary",
        "label": "שלב 5 — מסכמים ולוקחים הלאה",
        "shortLabel": "סיכום",
        "description": "מחברים את מה שנאמר, מה זוהה, ומה לוקחים לסבב הבא."
      }
    ],
    "supportRailMode": "guided-explanation",
    "settingsGroups": [
      "what-to-practice",
      "session-load",
      "categories",
      "advanced"
    ],
    "mobilePriorityOrder": [
      "start",
      "purpose",
      "helper-steps",
      "main",
      "support"
    ],
    "wrapper": {
      "pageTitle": "Classic Classic - Meta Model Trainer",
      "mountId": "classic-classic-app",
      "loadingTitle": "טוען את Classic Classic...",
      "loadingText": "מכין את מסך זיהוי התבניות עם שלבים, משוב והסבר יציב.",
      "errorTitle": "שגיאה בטעינת Classic Classic",
      "navLinks": [
        {
          "href": "index.html",
          "label": "חזרה לדף הראשי"
        },
        {
          "href": "classic2_trainer.html",
          "label": "Classic 2"
        },
        {
          "href": "iceberg_templates_trainer.html",
          "label": "Iceberg Templates"
        },
        {
          "href": "scenario_trainer.html",
          "label": "$1תמונות מחיי היום"
        }
      ],
      "accent": {
        "primary": "#2563eb",
        "border": "#bfdbfe",
        "glow": "rgba(37,99,235,0.16)",
        "background": "radial-gradient(circle at 15% 12%, #dbeafe 0%, transparent 38%), radial-gradient(circle at 88% 18%, #e0f2fe 0%, transparent 34%), radial-gradient(circle at 80% 80%, #fef3c7 0%, transparent 30%), linear-gradient(160deg, #eff6ff, #f8fafc 60%, #fff7ed)"
      },
      "standalone": {
        "htmlFile": "classic_classic_trainer.html",
        "manifestKey": "_classic_classic",
        "assetVersionGlobalKey": "__CC_ASSET_V__",
        "css": [
          "css/style.css",
          "css/classic-classic.css",
          "css/ui-enhancements.css",
          "css/meta-model-redesign.css"
        ],
        "scripts": [
          "js/classic-classic-config.js",
          "js/classic-classic-rng.js",
          "js/classic-classic-engine.js",
          "js/classic-classic-app.js"
        ]
      }
    }
  },
  "iceberg-templates": {
    "id": "iceberg-templates",
    "title": "קצה קרחון / עצי הבחנה",
    "subtitle": "ממיינים אמירה לתוך מבנה חשיבה, רואים איך העץ מסתעף, ובודקים חלופות במקום להינעל על פירוש אחד.",
    "familyLabel": "משפחת עצים וסכמות",
    "quickStartLabel": "כניסה לאימון",
    "startActionLabel": "התחל אימון",
    "settingsTitle": "הגדרות Iceberg Templates",
    "settingsSubtitle": "בוחרים איך להיכנס לאימון, אילו עזרי עבודה יישארו פתוחים, ואיך ייראה הסבב הבא.",
    "helperSteps": [
      {
        "title": "1. קוראים את האמירה",
        "description": "רואים את המשפט המלא ולא רק טוקן בודד."
      },
      {
        "title": "2. בוחרים מבנה וממקמים עוגן",
        "description": "מחליטים איזה סוג עץ מתאים וממקמים בתוכו עוגן אחד."
      },
      {
        "title": "3. פותחים ענף ובודקים חלופה",
        "description": "רואים הסתעפות, בודקים אפשרות נוספת, ולוקחים כיוון לשיחה אמיתית."
      }
    ],
    "processSteps": [
      {
        "id": "read",
        "label": "1. קוראים את האמירה",
        "shortLabel": "קוראים",
        "description": "קולטים את המשפט המלא ולא רק טוקן בודד."
      },
      {
        "id": "choose",
        "label": "2. בוחרים מבנה",
        "shortLabel": "מבנה",
        "description": "מחליטים איזה סוג עץ מתאים לבדיקה."
      },
      {
        "id": "place",
        "label": "3. משבצים את העוגן",
        "shortLabel": "משבצים",
        "description": "ממקמים את המילה או הביטוי בתוך המבנה."
      },
      {
        "id": "reveal",
        "label": "4. רואים את ההסתעפות",
        "shortLabel": "הסתעפות",
        "description": "מבינים מה המבנה פותח ומה עוד יכול להתפצל."
      },
      {
        "id": "branch",
        "label": "5. בודקים חלופה",
        "shortLabel": "חלופה",
        "description": "שואלים מה קורה אם בוחרים ענף אחר או פירוש אחר."
      }
    ],
    "supportRailMode": "branching-tree",
    "settingsGroups": [
      "entry-mode",
      "scenario",
      "workspace-aids",
      "advanced"
    ],
    "mobilePriorityOrder": [
      "start",
      "purpose",
      "helper-steps",
      "main",
      "support"
    ],
    "wrapper": {
      "pageTitle": "Iceberg Templates - Iceberg / Branch Trees",
      "mountId": "iceberg-templates-root",
      "loadingTitle": "טוען את קצה הקרחון...",
      "loadingText": "מכין את סביבת העבודה של עצי הבחנה, הסתעפויות וחלופות.",
      "errorTitle": "שגיאה בטעינת Iceberg Templates",
      "navLinks": [
        {
          "href": "index.html",
          "label": "חזרה לדף הראשי"
        },
        {
          "href": "classic2_trainer.html",
          "label": "Classic 2"
        },
        {
          "href": "classic_classic_trainer.html",
          "label": "Classic Classic"
        },
        {
          "href": "scenario_trainer.html",
          "label": "$1תמונות מחיי היום"
        }
      ],
      "accent": {
        "primary": "#92400e",
        "border": "#fde68a",
        "glow": "rgba(245,158,11,0.16)",
        "background": "radial-gradient(circle at 10% 8%, #fef3c7, #fffaf0 35%, #f8fafc)"
      },
      "standalone": {
        "htmlFile": "iceberg_templates_trainer.html",
        "manifestKey": "_iceberg",
        "bundlePath": "js/iceberg-templates-trainer.bundle.js",
        "buildMetaGlobalKey": "__ICEBERG_TEMPLATES_BUILD_META__",
        "assetVersionGlobalKey": "__ICEBERG_TEMPLATES_ASSET_V__",
        "css": [
          "css/meta-model-redesign.css",
          "css/ui-enhancements.css"
        ]
      }
    }
  },
  "scenario-trainer": {
    "id": "scenario-trainer",
    "title": "$1תמונות מחיי היום",
    "subtitle": "נכנסים לסצנה אנושית, בוחרים תגובה אחת, ורואים איך היא נוחתת רגשית ומה נפתח במודל המטה-מודלי.",
    "familyLabel": "משפחת הסימולטורים",
    "quickStartLabel": "מתחילים שיחה",
    "startActionLabel": "התחל סשן",
    "settingsTitle": "הגדרות $1תמונות מחיי היום",
    "settingsSubtitle": "מכווננים תחום, רמה, אורך סשן וכלי עזר, בלי לפרק את הדיאלוג לפני שהוא מתחיל.",
    "helperSteps": [
      {
        "title": "1. בחר/י תחום או השאר/י ברירת מחדל",
        "description": "אפשר להתחיל מיד, או לכוונן את הסשן הבא."
      },
      {
        "title": "2. קרא/י את הפתיחה ובחר/י תגובה",
        "description": "קודם רואים איך זה נוחת בשיחה אמיתית."
      },
      {
        "title": "3. רואים תוצאה, מעמיקים, וממשיכים",
        "description": "אחרי המשוב אפשר לפתוח מפת עומק או לעבור לסצנה הבאה."
      }
    ],
    "processSteps": [
      {
        "id": "scene",
        "label": "1. שומעים את הסצנה",
        "shortLabel": "סצנה",
        "description": "רואים מה ומי לוחץ ברגע הזה."
      },
      {
        "id": "reply",
        "label": "2. בוחרים תגובה",
        "shortLabel": "תגובה",
        "description": "בודקים איזו תגובה מקדמת קשר ובהירות."
      },
      {
        "id": "impact",
        "label": "3. רואים איך זה נוחת",
        "shortLabel": "השפעה",
        "description": "קוראים איך הצד השני עשוי לקלוט את התגובה."
      },
      {
        "id": "clarify",
        "label": "4. פותחים את הניתוח",
        "shortLabel": "עומק",
        "description": "רק אחרי החוויה האנושית פותחים את מה שהיה עמום."
      },
      {
        "id": "continue",
        "label": "5. ממשיכים לסצנה הבאה",
        "shortLabel": "המשך",
        "description": "לוקחים את הדיוק לשיחה הבאה."
      }
    ],
    "supportRailMode": "dialogue-meta",
    "settingsGroups": [
      "domain-focus",
      "difficulty",
      "session-load",
      "helpers"
    ],
    "mobilePriorityOrder": [
      "start",
      "purpose",
      "helper-steps",
      "main",
      "support"
    ],
    "wrapper": {
      "pageTitle": "Scenario Trainer - Meta Model Dialogue Simulator",
      "mountId": "scenario-trainer-root",
      "loadingTitle": "טוען את סימולטור הסצנות...",
      "loadingText": "מכין את סביבת הדיאלוג עם בחירות, משוב ופירוק עומק במקום אחד.",
      "errorTitle": "שגיאה בטעינת $1תמונות מחיי היום",
      "navLinks": [
        {
          "href": "index.html",
          "label": "חזרה לדף הראשי"
        },
        {
          "href": "classic2_trainer.html",
          "label": "Classic 2"
        },
        {
          "href": "classic_classic_trainer.html",
          "label": "Classic Classic"
        },
        {
          "href": "iceberg_templates_trainer.html",
          "label": "Iceberg Templates"
        }
      ],
      "accent": {
        "primary": "#0f766e",
        "border": "#99f6e4",
        "glow": "rgba(15,118,110,0.16)",
        "background": "radial-gradient(circle at 12% 10%, #ccfbf1, transparent 34%), radial-gradient(circle at 88% 18%, #fef3c7, transparent 30%), linear-gradient(165deg, #f0fdfa 0%, #f8fafc 60%, #fff7ed 100%)"
      },
      "standalone": {
        "htmlFile": "scenario_trainer.html",
        "manifestKey": "_scenario_trainer",
        "css": [
          "css/style.css",
          "css/scenario-trainer.css",
          "css/ui-enhancements.css",
          "css/meta-model-redesign.css"
        ],
        "scripts": [
          "js/scenario-trainer-app.js"
        ]
      }
    }
  }
};

export default TRAINER_PLATFORM_CONTRACTS;
